INSTALLER_DIR=${WECUBE_HOME}/installer
WECUBE_PLUGIN_BASE_MOUNT_PATH=${WECUBE_HOME}/plugins/mnt

PUBLIC_DOMAIN=${PORTAL_ENTRYPOINT}:19090
DEFAULT_ADMIN_USERNAME=umadmin
DEFAULT_ADMIN_PASSWORD=umadmin

MONITOR_AGENT_PORT=9100
WECUBE_SERVER_JMX_PORT=19101

S3_URL=http://${S3_HOST}:9000
S3_ACCESS_KEY=access_key
S3_SECRET_KEY=secret_key

PLUGIN_CMDB_DB_NAME=wecmdb_pro
