---

- name: Build mysql-docker env file
  ansible.builtin.template:
    src: mysql-docker.env.j2
    dest: &env_file "{{ installer_dir }}/mysql-docker.env"

- name: Invoke installer mysql-docker
  ansible.builtin.command:
    chdir: "{{ installer_dir }}"
    argv:
      - ./invoke-installer.sh
      - *env_file
      - mysql-docker
